# Generated by Django 4.0.6 on 2022-07-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Caring Date')),
                ('care', models.CharField(choices=[('W', 'Watering'), ('S', 'Sun light'), ('N', 'Nutrition')], default='W', max_length=1)),
                ('hoya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hoya')),
            ],
        ),
    ]
