# Generated by Django 4.0.6 on 2022-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cultivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cultivation',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='care',
            field=models.CharField(choices=[('W', 'Watering'), ('S', 'Sun light'), ('N', 'Nutrition')], default='W', max_length=1, verbose_name='Care Period'),
        ),
        migrations.AddField(
            model_name='hoya',
            name='planters',
            field=models.ManyToManyField(to='main_app.planter'),
        ),
    ]
